export const ROLES = {
  CITIZEN: 'CITIZEN',
  UNIVERSITY: 'UNIVERSITY',
  INDUSTRY: 'INDUSTRY',
  EVALUATOR: 'EVALUATOR',
  GOVERNMENT: 'GOVERNMENT',
  ADMIN: 'ADMIN',
};

export const PROBLEM_STATUS = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  CHALLENGE_CREATED: 'CHALLENGE_CREATED',
  SOLVED: 'SOLVED',
  REJECTED: 'REJECTED',
};

export const CHALLENGE_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  UNDER_EVALUATION: 'UNDER_EVALUATION',
  IN_PILOT: 'IN_PILOT',
  DEPLOYED: 'DEPLOYED',
  CLOSED: 'CLOSED',
};

export const SOLUTION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  SHORTLISTED: 'SHORTLISTED',
  EVALUATED: 'EVALUATED',
  SPONSORED: 'SPONSORED',
  PILOT_READY: 'PILOT_READY',
  DEPLOYED: 'DEPLOYED',
};

export const PILOT_STATUS = {
  PROPOSED: 'PROPOSED',
  APPROVED: 'APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  VERIFIED: 'VERIFIED',
  DEPLOYED: 'DEPLOYED',
  FAILED: 'FAILED',
};
